### PR TITLE
Finish mobile version

### PR DESCRIPTION
**Pull request by dev-mamun**
Add Three new section

1. Recent Work
2. About
3. Capability

### CODE REVIEW

**Review by Kossi-stack — CHANGES_REQUESTED** [review]
## Hi @dev-mamun,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 - [ ] Kindly use button or a tag for "see project in works section".
- [ ] Kindly wrap about me into a section.
- [ ] Kindly add "Get resume" into a tag or button don't put it in p tag.
- [ ] Kindly use display grid for the main container works section.

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by dev-mamun** [comment]
Kindly use button or a tag for "see project in works section". => its already on a tag "<a href="#" class="c-btn">See Project</a>"
Kindly add "Get resume" into a tag or button don't put it in p tag. => same "<a href="#" class="c-btn">Get My Resume</a>"
Kindly use display grid for the main container works section => do you mean this "display: grid;" rather then this "display: flex;" 

@Kossi-stack your request not clear. please explain in details

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi @dev-mamun   , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Professional  README
✔️ Good commit messages

almost

## Required Changes ♻️

- [x] Kindly I recommend you to use `hx` (h2,h3,h4,h5 etc ) header tag instead of `h1` tag for "My Recent Works" and "About myself" for purpose of SEO optimization, All of the important pages on your site should have one `H1` tags to draw in the reader and give a clear indication of the content on the page.

https://github.com/dev-mamun/microverse-portfolio/blob/3392a29a77008fd8081c9ca210def5f039735fa0/index.html#L75

https://github.com/dev-mamun/microverse-portfolio/blob/3392a29a77008fd8081c9ca210def5f039735fa0/index.html#L170

- [x] Good job for using the `a`  tag for The button (e.g., "See project") but I recommend you to remove the `p` tag and As stated the project requirement Kindly Implement the button interactions , follow the button styling: Active, Hover and Pressed (see design).
- https://github.com/dev-mamun/microverse-portfolio/blob/3392a29a77008fd8081c9ca210def5f039735fa0/index.html#L163
- https://github.com/dev-mamun/microverse-portfolio/blob/3392a29a77008fd8081c9ca210def5f039735fa0/index.html#L176

  Capture

- [x] Kindly I recommend you to use **one section tag for the container of "About me"** section , So use `div` tag for technology categories ("Languages", "Frameworks" and "Skills") instead of section tag.
- https://github.com/dev-mamun/microverse-portfolio/blob/3392a29a77008fd8081c9ca210def5f039735fa0/index.html#L168-L236


_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by amejid — COMMENTED** [review]
Hi @dev-mamun, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failing linter check. Kindly fix the issue.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by amejid — APPROVED** [review]
Hi @dev-mamun, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
